name: Build and Test
on:
    pull_request: {}
    push:
        branches: [develop, staging, master]
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
jobs:
    # fetch:
    #     uses: ./.github/workflows/build_prepare.yaml
    #     permissions:
    #         contents: read
    #     with:
    #         config: ${{ github.event.pull_request.base.ref == 'develop' && 'elecord.app/nightly' || 'elecord.app/release' }}
    #         version: ${{ github.event.pull_request.base.ref == 'develop' && 'develop' || '' }}

    # windows:
    #     needs: fetch
    #     name: Windows
    #     uses: ./.github/workflows/build_windows.yaml
    #     strategy:
    #         matrix:
    #             # arch: [x64, ia32]
    #             arch: [x64]
    #     with:
    #         arch: ${{ matrix.arch }}

    # linux:
    #     needs: fetch
    #     name: "Linux (${{ matrix.arch }}) (sqlcipher: ${{ matrix.sqlcipher }})"
    #     uses: ./.github/workflows/build_linux.yaml
    #     strategy:
    #         matrix:
    #             # sqlcipher: [system, static]
    #             sqlcipher: [static]
    #             # arch: [amd64, arm64]
    #             arch: [amd64]
    #     with:
    #         config: ${{ github.event.pull_request.base.ref == 'develop' && 'elecord.app/nightly' || 'elecord.app/release' }}
    #         sqlcipher: ${{ matrix.sqlcipher }}
    #         arch: ${{ matrix.arch }}

    # macos:
    #     needs: fetch
    #     name: macOS
    #     uses: ./.github/workflows/build_macos.yaml

    # release:
    #         name: Release
    #         uses: ./.github/workflows/build_release.yaml

    packages:
            name: Update packages.elecord.app
            uses: ./.github/workflows/build_site.yaml

