# This action uploads the newly built artifacts as a GitHub release.
# Then creating the Cloudflare pages site with redirects to the new release files.

on:
    workflow_call: {}
permissions: {}
jobs:
    release:
        name: Release
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4

            # - uses: actions/download-artifact@v4
            #   with:
            #       name: win-x64 # .zip from build_windows

            # download file from https://github.com/hazzuk/elecord-desktop/releases/download/test/win-x64.zip
            - name: Download win-x64.zip
              run: |
                  curl -L https://github.com/hazzuk/elecord-desktop/releases/download/test/win-x64.zip -o win-x64.zip

            - name: Get app version
              run: |
                  echo "version=$(cat package.json | jq -r .version)" >> $GITHUB_ENV

            - name: Extract files
              run: |
                  unzip -q win-x64.zip -d ./artifacts
                  ls -la ./artifacts/squirrel-windows

            - name: Create release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: v${{ env.VERSION }}
                  name: v${{ env.VERSION }}
                  draft: false
                  prerelease: false
                  files: |
                      ./artifacts/extracted/squirrel-windows/elecord Setup ${{ env.VERSION }}.exe
                      ./artifacts/extracted/squirrel-windows/elecord-desktop-${{ env.VERSION }}-full.nupkg
                      ./artifacts/extracted/squirrel-windows/RELEASES
                  body: "[See the full elecord changelog](https://github.com/elecordapp/elecord-web/releases/tag/v${{ env.VERSION }})"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
